[package]
name = "test_gh_actions"
version = "0.1.2-alpha.0"
edition = "2018"
description = "Indexes stuff"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]
license = "GPL-3.0-only"

[dependencies]
